### ISSUE TITLE
Investigate publishing results of CI to the open

### ISSUE THREAD

**Issue by mbianco** [GridTools/_GT_Tasks#27]
Talk to CI group and figure out if solution is possible.

**Comment by tehrengruber** [comment]
Publishing the results has turned out be no problem at all. The runners outputs are already published on https://gitlab.com/cscs-ci/gridtools/gt4py-ci/-/pipelines publicly. Missing pieces for the CI now are just setting up a trigger for the CI (either sync repo or trigger via comment) and pushing the benchmark results to github pages (either seperate repo or branch in main repo).
