### ISSUE TITLE
Discuss algorithms for location-type mappings.

### ISSUE THREAD

**Issue by mbianco** [GridTools/_GT_Tasks#38]
We need to understand what should be the minimal required information needed for deriving the location-type mappings in "unstructured" cases, and how we could take existing meshes that already provide more.

**Comment by tehrengruber** [comment]
**Input data (option 1):**
- C2V connectivity (minimum input from mesh generators in general)
- E2V (optional) should be supported as additional input since some mesh generators provide us with this connectivity and we need it to retain the numbering of the edges

**Input data (option 2):**
- E2C (If not given generate from C2V using sorting algorithm)
- E2V

E2C and E2V map to fixed size of neighbors => dim(E) < dim(C) is not of concern.
For mesh interface discussed below you just use create edges and cells and add the mapping to the E2C connectivity.

**Conclusion** from discussion with Anton:
We go with option 2 as the algorithms to construct all connectivity are simple and have linear complexity. For the use case of constructing meshes from C2V connectivity we can then still rely on the more complex sorting algorithm.

**Appendix**:

Most popular connectivities:

```
# IFS-FVM (vertex centered)
E -> V
V -> E
# FEM
C -> V -> C
# ICON
E -> C -> V
```

Mesh interface
```python
mesh = Mesh()
# add_vertex(x, y)
v1 = mesh.add_vertex(0, 0)
v2 = mesh.add_vertex(0, 1)
v3 = mesh.add_vertex(1, 1)
v4 = mesh.add_vertex(1, 0)

# add_cell(vertices...)
c1 = mesh.add_cell(v1, v2, v3, v4)
c2 = mesh.add_cell(v4, v1, v2, v3)

for cell in mesh.cells:
  id(cell)
  vertices(cell)

for edge in mesh.edges:
  vertices(edge)

for id, conn in graph(mesh.topology[Cell(), Vertex()]):
  id : Id[Cell]
  conn : Connectivity[Cell, Vertex] # like a Vector with type information
  # e.g. conn = [v1, v2, v3, v4] # invariant: order is the same as user provided (not strictly necessary, but easy and no apparent drawbacks)

for id, conn in graph(mesh.geometry[Cell()]):
  id : Id[Cell]
  conn : Geometry[Cell] # like a Matrix with type information
  # e.g. conn = [0, 0, 1, 1; 0 1 1 0]
```
